### ISSUE TITLE
[SyntaxError: Unexpected token s] while running gulp

### ISSUE THREAD

**Issue by mogahector** [mmorga/generator-ramlapi#1]
$ gulp
[19:38:21] Using gulpfile ~/Documents/architecture/ACT/contract/gulpfile.js
[19:38:21] Starting 'jsonlint'...
[19:38:21] Finished 'jsonlint' after 11 ms
[19:38:21] Starting 'apidoc'...
[19:38:21] Error! schemas/0/transactionTypes [SyntaxError: Unexpected token s]
 schema/transactionTypes.json

{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "transactionTypes.json",
  "type": "object",
  "properties": {
    "transactionTypes": {
      "id": "http://jsonschema.net/transactionTypes",
      "type": "array",
      "items": {
        "id": "http://jsonschema.net/transactionTypes/1",
        "type": "string"
      },
      "required": [
        "1"
      ]
    }
  },
  "required": [
    "transactionTypes"
  ]
}

**Comment by mogahector** [comment]
Have you seen this error before?

**Comment by mmorga** [comment]
for type array, you probably meant:

```json
"minItems": 1
```

instead of:

```json
"required": "1"
```

Not sure about the error message. I'll look into it.
